config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contractors

  resources :works

  resources :tenants

  resources :landlords

  resources :properties

  root 'welcome#index'
  get 'get_data.json' => 'welcome#get_data'

end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :property
	validates :property_id, presence: true

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @property = Property.all
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:job_type, :raised_date, :due_date, :property_id)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @work.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h4>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :job_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :job_type, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :raised_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :raised_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :due_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_id, :class => "col-sm-2 control-label" %>

    <div class="col-sm-10">
      <%= f.collection_select :property_id, Property.all, :id, :address %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/works/edit.html.erb
<div class="page-header">
  <%= link_to works_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @work, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing work</h1>
</div>

<%= render 'form' %>

app/views/works/index.html.erb
<div class="page-header">
  <%= link_to new_work_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Work
  <% end %>
  <h1>Outstanding Contracts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Job Type</th>
            <th>Raised date</th>
            <th>Due date</th>
            <th>Property Address</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @works) do |work| %>
            <td><%= work.job_type %></td>
            <td><%= work.raised_date %></td>
            <% if work.due_date < Date.current + 7 %>
              <td class="due-within-week"><%= work.due_date %></td>
              <% else %>
                <td><%= work.due_date %></td>
            <% end %>
            <td><%= work.property.address %></td>
            <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/works/new.html.erb
<div class="page-header">
  <%= link_to works_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Work Order</h1>
</div>

<%= render 'form' %>

app/views/works/show.html.erb
<div class="page-header">
  <%= link_to url_for(:back), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_work_path(@work), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show work</h1>
</div>

<dl class="dl-horizontal">
  <dt>Type:</dt>
  <dd><%= @work.job_type %></dd>

  <dt>Raised date:</dt>
  <dd><%= @work.raised_date %></dd>

  <dt>Due date:</dt>
  <dd><%= @work.due_date %></dd>

  <dt>Property:</dt>
  <dd><%= @work.property_id %></dd>

</dl>