config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contractors

  resources :works

  resources :tenants

  resources :landlords

  resources :properties

  root 'welcome#index'
  get 'get_data.json' => 'welcome#get_data'

end

app/models/property.rb
class Property < ActiveRecord::Base
  # The following prohibits all property deletions
  # before_destroy :check_for_works

  # def check_for_works
  #   errors.add :base, "Close any outstanding works before deletion."
  #   false
  # end


	geocoded_by :address
	before_validation :geocode, :if => :address_changed?

	belongs_to :landlord
	has_one :tenant
	
	validates :latitude, :longitude, :landlord, presence: true
	accepts_nested_attributes_for :landlord, :tenant

	has_many :works
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @tenant = Tenant.all
    @jobs = Work.all
    @properties = Property.all    
    @properties.each do |prop|
      @jobs.each do |job|
        if job.property_id == prop.id
          puts "setting property id #{prop.id} to active_job = 1"
          # prop.active_job = "1"
          prop.update(active_job: "1")
          break
        else
          puts "setting property id #{prop.id} to active_job = 0"
          prop.active_job = "0"
        end
      end
    end
  end
  # GET /properties/1
  # GET /properties/1.json
  def show


    @property = Property.find(params[:id])
    @property_marker = Gmaps4rails.build_markers(@property) do |prop, marker|
      marker.lat prop.latitude
      marker.lng prop.longitude
      marker.infowindow prop.address
    @tenant = Tenant.all
    @job_count = Work.where(property_id:params[:id]).count
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        puts "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<it didn't save"
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:address, :landlord_id, :longitude, :latitude, :active_job)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @property.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h4>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :landlord_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :landlord_id, Landlord.all, :id, :landlord_full_name %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="page-header">
  <%= link_to properties_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @property, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing property</h1>
</div>

<%= render 'form' %>

app/views/properties/index.html.erb
<div class="page-header">
  <%= link_to new_property_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Property
  <% end %>
  <h1>Managed Property List</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Address</th>
            <th>Landlord</th>
            <th>Tenant</th>
            <th>End of Lease</th>
            <th>Works Active?</th>
            <th>Admin</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @properties) do |property| %>
            <td><%= link_to property.address, property %></td>
            <td><%= link_to property.landlord.first_name + ' ' + property.landlord.last_name, property.landlord %></td>
            <%= @tenant.find_each do |tenant| %>
              <% if tenant.property_id == property.id %>
                <td><%= link_to tenant.first_name + ' ' + tenant.last_name, 'tenants/' + tenant.id.to_s %></td>
                <% @tenant_boolean = true %>
                <% break %>
              <% else %>
                <% @tenant_boolean = false %>
              <% end %>
            <% end %>
            <% if @tenant_boolean == false || @tenant.count == 0 %>
              <td>No Tenant!</td>
            <% end %>
            <%= @tenant.find_each do |tenant| %>
              <% if tenant.property_id == property.id %>
                <td><%= tenant.lease_end %></td>
                <% @tenant_lease_boolean = true %>
                <% break %>
              <% else %>
                <% @tenant_lease_boolean = false %>
              <% end %>
            <% end %>
            <% if @tenant_lease_boolean == false || @tenant.count == 0%>
              <td>N/A</td>
            <% end %>
            <% if property.active_job.to_i > 0 %>
              <td>Yes</td>
            <% else %>
              <td> No </td>
            <% end %>
        
        <td><%= link_to 'Edit', edit_property_path(property) %> | <%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure? This cannot be undone!' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/properties/new.html.erb
<div class="page-header">
  <%= link_to properties_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New property</h1>
</div>

<%= render 'form' %>

app/views/properties/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<%= stylesheet_link_tag 'show' %>



<div class="container">
  <div id="map-container" class="row" style="padding-top:50px">
    <div class="col-md-12" id="map" style="height:400px">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1><%= @property.address %></h1>
    </div>
  </div>
  <div id="landlord-tenant-header" class="row">
    <div class="col-md-4">
    <h2>Landlord Information</h2>
    </div>
    <div class="col-md-4">
    <h2>Tenant Information</h2>
    </div>
    <div class="col-md-4">
    <h2>Outstanding Work</h2>
    </div>
  </div>
  <div id="landlord-tenant-infos" class="row">
    <div class="col-md-4">
      <ul class="property-details-list">
        <li>Landlord Name: <%= link_to @property.landlord.first_name + ' ' + @property.landlord.last_name, '/landlords/' + @property.landlord.id.to_s %></li>
        <li>Email: <%= @property.landlord.email %></li>
        <li>Tel: <%= @property.landlord.tel %></li>
        <li>Address: <%= @property.landlord.address %></li>
        <li>Customer Since: <%= @property.landlord.date_registered.to_formatted_s(:long) %></li>
      </ul>
    </div>
    <div class="col-md-4">
      <ul class="property-details-list">
            <%= @tenant.find_each do |tenant| %>
              <% if tenant.property_id == @property.id %>
                <li><%= tenant.first_name + ' ' + tenant.last_name %></li>
                <li>Email: <%= tenant.email %></li>
                <li>Tel: <%= tenant.tel %></li>
                <li>Lease Started: <%= tenant.lease_commenced.to_formatted_s(:long) %></li>
                <% if tenant.lease_end < 0.day.ago %>
                  <li>Lease ended on <%= tenant.lease_end.to_formatted_s(:long) %>
                <% else %> 
                  <li>Lease Ends: <%= tenant.lease_end.to_formatted_s(:long)%> (<%= (Date.today - tenant.lease_end).to_i.abs / 7 %> Weeks Left)</li>
                <% end %>
                <% @tenant_boolean = true %>
                <% break %>
              <% else %>
                <% @tenant_boolean = false %>
              <% end %>
            <% end %>
            <% if @tenant_boolean == false %>
              <li>No Tenant!</li>
              <li>No Lease Pending!</li> <!-- change this to be dynamic if there is a lease coming up -->
            <% end %>
        
      </ul>
    </div>
    <div class="col-md-4">
      <ul class="property-details-list">
        <% if @property.active_job == nil %>
        <li>There are currently <strong>no</strong> work orders outstanding on this property.</li>
        <% else %>
        <li>There are currently <%= @job_count %> work orders outstanding on this property.</li>
        <% end %>
    </div>
  </div>

</div>

<script type="text/javascript">
mapStyle = [{"featureType":"landscape","stylers":[{"color":"#6c8080"},{"visibility":"simplified"}]},{"featureType":"administrative","elementType":"labels.text","stylers":[{"visibility":"on"}]},{"featureType":"road","stylers":[{"visibility":"simplified"}]},{"featureType":"poi","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road","elementType":"labels.icon","stylers":[{"visibility":"on"}]},{"featureType":"transit","elementType":"labels","stylers":[{"visibility":"on"}]},{"elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","stylers":[{"color":"#d98080"},{"hue":"#eeff00"},{"lightness":100},{"weight":1.5}]}]
handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles: mapStyle}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @property_marker.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});
</script>