config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contractors

  resources :works

  resources :tenants

  resources :landlords

  resources :properties

  root 'welcome#index'
  get 'get_data.json' => 'welcome#get_data'

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
	has_many :works
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:company_name, :industry_type, :email, :tel, :jobs_completed, :jobs_feedback_good, :jobs_feedback_bad)
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_form.html.erb
<%= form_for(@contractor, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @contractor.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@contractor.errors.count, "error") %> prohibited this contractor from being saved:</h4>

      <ul>
      <% @contractor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :industry_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :industry_type, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tel, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobs_completed, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :jobs_completed, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobs_feedback_good, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :jobs_feedback_good, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobs_feedback_bad, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :jobs_feedback_bad, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<div class="page-header">
  <%= link_to contractors_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @contractor, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing contractor</h1>
</div>

<%= render 'form' %>

app/views/contractors/index.html.erb
<div class="page-header">
  <%= link_to new_contractor_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Contractor
  <% end %>
  <h1>Listing contractors</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Company name</th>
            <th>Industry type</th>
            <th>Email</th>
            <th>Tel</th>
            <th>Jobs completed</th>
            <th>Positive Feedback</th>
            <th>Negative Feedback</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @contractors) do |contractor| %>
            <td><%= contractor.company_name %></td>
            <td><%= contractor.industry_type %></td>
            <td><%= contractor.email %></td>
            <td><%= contractor.tel %></td>
            <td><%= contractor.jobs_completed %></td>
            <td><%= contractor.jobs_feedback_good %></td>
            <td><%= contractor.jobs_feedback_bad %></td>
            <td><%= link_to 'Show', contractor %></td>
        <td><%= link_to 'Edit', edit_contractor_path(contractor) %></td>
        <td><%= link_to 'Destroy', contractor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contractors/new.html.erb
<div class="page-header">
  <%= link_to contractors_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New contractor</h1>
</div>

<%= render 'form' %>

app/views/contractors/show.html.erb
<div class="page-header">
  <%= link_to contractors_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_contractor_path(@contractor), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show contractor</h1>
</div>

<dl class="dl-horizontal">
  <dt>Company name:</dt>
  <dd><%= @contractor.company_name %></dd>

  <dt>Industry type:</dt>
  <dd><%= @contractor.industry_type %></dd>

  <dt>Email:</dt>
  <dd><%= @contractor.email %></dd>

  <dt>Tel:</dt>
  <dd><%= @contractor.tel %></dd>

  <dt>Jobs completed:</dt>
  <dd><%= @contractor.jobs_completed %></dd>

  <dt>Jobs feedback good:</dt>
  <dd><%= @contractor.jobs_feedback_good %></dd>

  <dt>Jobs feedback bad:</dt>
  <dd><%= @contractor.jobs_feedback_bad %></dd>

</dl>