config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contractors

  resources :works

  resources :tenants

  resources :landlords

  resources :properties

  root 'welcome#index'
  get 'get_data.json' => 'welcome#get_data'

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
	has_many :properties
  def landlord_full_name
    first_name << " " << last_name
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
    @property_count = Property.where(landlord_id: @landlord.id).count
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:first_name, :last_name, :email, :tel, :address, :date_registered, :property_id)
    end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/landlords/_form.html.erb
<%= form_for(@landlord, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @landlord.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h4>

      <ul>
      <% @landlord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tel, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_registered, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date_registered, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :property_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<div class="page-header">
  <%= link_to landlords_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @landlord, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing landlord</h1>
</div>

<%= render 'form' %>

app/views/landlords/index.html.erb
<div class="page-header">
  <%= link_to new_landlord_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Landlord
  <% end %>
  <h1>Landlord Registry</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Tel</th>
            <th>Address</th>
            <th>Date registered</th>
            <th>Admin</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @landlords) do |landlord| %>
            <td><%= link_to landlord.first_name + ' ' + landlord.last_name, landlord %></td>
            <td><%= landlord.email %></td>
            <td><%= landlord.tel %></td>
            <td><%= landlord.address %></td>
            <td><%= landlord.date_registered %></td>
            <td><%= link_to 'Show', landlord %> | <%= link_to 'Edit', edit_landlord_path(landlord) %> | <%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/landlords/new.html.erb
<div class="page-header">
  <%= link_to landlords_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New landlord</h1>
</div>

<%= render 'form' %>

app/views/landlords/show.html.erb
<div class="page-header">
  <%= link_to url_for(:back), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_landlord_path(@landlord), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @landlord.first_name + " " + @landlord.last_name %></h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @landlord.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @landlord.last_name %></dd>

  <dt>Email:</dt>
  <dd><%= mail_to @landlord.email, @landlord.email %></dd>

  <dt>Tel:</dt>
  <dd><%= @landlord.tel %></dd>

  <dt>Address:</dt>
  <dd><%= @landlord.address %></dd>

  <dt>Date registered:</dt>
  <dd><%= @landlord.date_registered %></dd>

  <dt>Property Count:</dt>
  <dd><%= @property_count %></dd>

</dl>